language: node_js

node_js: stable

branches:
    only:
        - hexo
cache:
    apt: true
    directories:
        - node_modules

before_install:
    - git config --global user.name "Santino-Wu"
    - git config --global user.email "santinowu.wsq@gmail.com"
    - npm install -g hexo-cli

install:
    - npm install

script:
    - hexo clean
    - hexo generate

after_success:
    - cd ./public
    - git init
    - git add --all .
    - git commit -m "[`date '+%F %T'`] Updated by Travis CI"
    - git push --quiet --force https://${GH_TOKEN}@github.com/Santino-Wu/Santino-Wu.github.io.git master
